spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    org.springframework: INFO
    com.yarmak: INFO

management:
  security:
    enabled: false

---
spring:
  profiles: test

logging:
  level:
    org.springframework: DEBUG

---
spring:
  profiles: dev

logging:
  level:
    org.springframework: ERROR

